export const ENDPOINT = {
  Root: '/api/v1',
  Auth: '/auth',
  Users: '/users',
  User: '/user',
  Game: '/game',
  Games: '/games',
  Genre: '/genre',
  Genres: '/genres',
  Review: '/review',
  Reviews: '/reviews',
  Profile: '/profile',
  Profiles: '/profiles',
  Platform: '/platform',
  Platforms: '/platforms',
};
